version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23
  build:
    commands:
      - ls -l
      - echo Building the Docker image...
      - docker build -t ${{ secrets.ECR_REPOSITORY_URI}}:${{ secrets.TAG}} .
      - echo Pushing the Docker image to ECR...
      - aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.REGION }}.amazonaws.com
      - docker push ${{ secrets.ECR_REPOSITORY_URI}}:${{ secrets.TAG }}
