version: 0.2

phases:
  pre_build:
    commands:
      - echo Checking if Docker is available...
      - docker version || (echo "Docker is not installed. Installing Docker..." && apt-get update && apt-get install -y docker-ce)
      - echo Starting Docker...
      - service docker start

  build:
    commands:
      - ls -l
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URI:$TAG .
      - echo Pushing the Docker image to ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - docker push $ECR_REPOSITORY_URI:$TAG
