# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       docker: 23
#   pre_build:
#     commands:
#       - echo Logging in to Amazon ECR...
#       - export DOCKER_REGISTRY_URL=$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
#       - export ECR_LOGIN_COMMAND=$(aws ecr get-login-password --region $REGION)
#       - echo $ECR_LOGIN_COMMAND | docker login --username AWS --password-stdin $DOCKER_REGISTRY_URL

#   build:
#     commands:
#       - echo Building the Docker image...
#       - docker build -t $ECR_REPOSITORY_URI:$TAG .
#   post_build:
#     commands:
#       - echo Pushing the Docker image to ECR...
#       - docker push $ECR_REPOSITORY_URI:$TAG

version: 0.2

phases:
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URI:$TAG .
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI:$TAG

artifacts:
  files:
    - '**/*'
